-- Copilot review round 2 (PR #23), CLAUDE.md "The relationship a predicate joins through must
-- itself be enforced": this file's own resolve_join_code/claim_join_code (below) are SECURITY
-- DEFINER, unauthenticated-reachable, and their password_reset branch trusts TWO invariants that
-- only drizzle/0020 (the is_resident/resident_profile_id pairing CHECK) and drizzle/0021 (the
-- one-membership-per-profile/per-account UNIQUE indexes) actually add — on a FRESH database that
-- applies migrations in order, a window would otherwise open between this file committing (the
-- functions live) and 0020/0021 committing (the invariants they trust exist). Re-runnable copies
-- of both go here, at the TOP, before any function: DROP CONSTRAINT IF EXISTS + ADD CONSTRAINT for
-- the CHECK, and CREATE UNIQUE INDEX IF NOT EXISTS for the two indexes — closing that window for a
-- database that has never seen 0020/0021 at all. 0020 and 0021 keep their own statements too, now
-- idempotent re-assertions for a database (dev included) that applied this file BEFORE these lines
-- existed — each of those files gets a one-line comment saying so. dev's own 0020/0021 are NOT
-- re-applied by this comment: nothing in 0019 needs re-running there, because 0020/0021 already
-- cover it (CLAUDE.md instruction for this fix).
ALTER TABLE "membership" DROP CONSTRAINT IF EXISTS "membership_resident_pairing";
--> statement-breakpoint
ALTER TABLE "membership" ADD CONSTRAINT "membership_resident_pairing" CHECK ("membership"."is_resident" = ("membership"."resident_profile_id" IS NOT NULL));
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "membership_resident_profile_id_unique" ON "membership" USING btree ("resident_profile_id") WHERE "membership"."resident_profile_id" IS NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "membership_account_id_unique" ON "membership" USING btree ("account_id");
--> statement-breakpoint

-- resident-settings design.md Decision 4 (Migration Plan). A join link gains a `purpose`
-- (`join` / `password_reset`); a reset link is a bound link naming an ACTIVE profile whose
-- account has no email (identity/password-reset). Steps 1-3 are a plain column/constraint add,
-- generated by drizzle-kit from schema.ts and hand-edited here to be re-runnable (DO ... EXCEPTION
-- WHEN duplicate_object for the CREATE TYPE, IF NOT EXISTS for the column, DROP CONSTRAINT IF
-- EXISTS before ADD CONSTRAINT). Steps 4-6 replace both SECURITY DEFINER functions and are a
-- HUMAN HAND-OFF (tasks.md 2.4): the harness refuses SECURITY DEFINER statements, so an agent can
-- apply only steps 1-3, and a human runs this WHOLE file afterwards in the Supabase SQL editor —
-- which is why every statement here, not only 1-3, is written to survive a partial prior run.
--
-- *** WHY DROP-THEN-CREATE, NOT `CREATE OR REPLACE` (drizzle/0015's lesson) ***
-- resolve_join_code gains an output column (`purpose`); claim_join_code gains an argument
-- (`p_purpose`). Both change the shape Postgres tracks as part of a function's return/argument
-- type, and `CREATE OR REPLACE FUNCTION` refuses that outright ("cannot change return type of
-- existing function / HINT: Use DROP FUNCTION first" — or, for an argument list, simply resolves
-- to a distinct overload instead of replacing anything, which is exactly the hazard Step 5 exists
-- to close). Both `claim_join_code(text)` (0013) and `claim_join_code(text, join_code_purpose)`
-- (any partial prior run of this file) are dropped before the single two-argument function is
-- created, so the OLD one-argument overload cannot survive beside the new one, still callable and
-- still ignoring purpose.
--
-- Ordering against the live constraints: the column arrives with its default ('join') BEFORE the
-- CHECK, so every existing row already satisfies it. The functions come last, so neither is ever
-- created in a shape that references a column that doesn't exist yet.

-- Step 1: the enum type. `CREATE TYPE` has no `IF NOT EXISTS` in this Postgres version, so
-- re-runnability comes from catching the "already exists" error instead (duplicate_object,
-- SQLSTATE 42710) — the same idiom this project already reaches for whenever a plain DDL clause
-- lacks its own guard.
DO $$ BEGIN
  CREATE TYPE "public"."join_code_purpose" AS ENUM('join', 'password_reset');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Step 2: the column itself. NOT NULL with a default, so every existing row becomes a joining
-- link with no backfill needed. IF NOT EXISTS so the whole file can be re-run after an agent
-- applied this step but had steps 4-6 refused by the permission layer.
ALTER TABLE "join_code_issuance" ADD COLUMN IF NOT EXISTS "purpose" "join_code_purpose" DEFAULT 'join' NOT NULL;
--> statement-breakpoint

-- Step 3: a password-reset link always names a profile — there is no such thing as a neutral
-- reset link, unlike a joining link, which may or may not be bound. Holds in raw SQL too: nothing
-- but this constraint stops a corrupt or hand-written row from minting a reset link naming
-- nobody, which resolve_join_code/claim_join_code would otherwise have to refuse defensively
-- rather than by construction. DROP CONSTRAINT IF EXISTS before ADD so a second run does not fail
-- on a duplicate constraint name.
ALTER TABLE "join_code_issuance" DROP CONSTRAINT IF EXISTS "join_code_issuance_reset_names_profile";
--> statement-breakpoint
ALTER TABLE "join_code_issuance" ADD CONSTRAINT "join_code_issuance_reset_names_profile" CHECK ("join_code_issuance"."purpose" = 'join' OR "join_code_issuance"."resident_profile_id" IS NOT NULL);
--> statement-breakpoint

-- *** HUMAN HAND-OFF FROM HERE (tasks.md 2.4): the agent harness refuses SECURITY DEFINER
-- statements. A human runs the rest of this file (or the whole file again — every statement above
-- is idempotent) in the Supabase SQL editor for flatmate-io-dev, as `postgres`. ***

-- Step 4: resolve_join_code, replaced to also return `purpose` and to judge a reset link's
-- validity, not only a joining one's. STABLE, non-consuming — unchanged in every other respect
-- from drizzle/0015's version for the joining branch.
DROP FUNCTION IF EXISTS resolve_join_code(text);
--> statement-breakpoint
CREATE FUNCTION resolve_join_code(p_code text) RETURNS TABLE (
  household_id uuid,
  issuance_id uuid,
  household_name text,
  bound_resident_profile_id uuid,
  bound_resident_display_name text,
  purpose join_code_purpose
)
LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT h.id, jci.id, h.name, rp.id, rp.display_name, jci.purpose
  FROM "join_code_issuance" jci
  JOIN "household" h ON h.id = jci.household_id
  -- The household predicate is NOT redundant with issueJoinCodeTx's/issuePasswordResetLink's own
  -- checks. This function is SECURITY DEFINER, so it runs past RLS, and it answers an
  -- UNAUTHENTICATED caller; there are no foreign keys in this schema, so nothing but application
  -- code keeps this column honest. Were a binding ever wrong — a bug, a hand-edited row, a bad
  -- backfill — the two output columns would disclose another household's profile id and display
  -- name to a stranger holding a code. With the predicate they come back null instead, which is
  -- the same outcome as a neutral link (an invalid reset link, for the reset branch below).
  LEFT JOIN "resident_profile" rp
    ON rp.id = jci.resident_profile_id AND rp.household_id = jci.household_id
  WHERE jci.code = p_code
    AND jci.deleted_at IS NULL
    AND jci.expires_at > now()
    AND jci.uses < jci.max_uses
    AND h.deleted_at IS NULL
    AND (
      -- A JOINING link, bound or neutral: unchanged from drizzle/0015. A BOUND joining link is
      -- valid only while the profile it names is still claimable, in its own household (third
      -- review of PR #17). `rp.id IS NOT NULL` additionally makes a CORRUPT binding (one pointing
      -- outside this household, which the join above already refuses to match) kill the link
      -- outright rather than letting it behave as a neutral one.
      (jci.purpose = 'join' AND (jci.resident_profile_id IS NULL OR (rp.id IS NOT NULL AND rp.status = 'prepared')))
      OR
      -- A RESET link (identity/password-reset): valid only while its named profile is ACTIVE, its
      -- membership is live (not revoked), and — the gap it closes — the account still has no
      -- email. Every join carries its own household_id predicate (CLAUDE.md "A SECURITY DEFINER
      -- function"): a corrupt membership or account row whose household_id differs must not make
      -- a reset link valid, exactly as a corrupt resident_profile binding must not above.
      -- `a.email IS NULL` is a predicate here, never an output column — the function discloses
      -- only the display name the person is greeted by (spec: "no email, account id or status is
      -- returned").
      (jci.purpose = 'password_reset' AND rp.id IS NOT NULL AND rp.status = 'active'
         AND EXISTS (
           SELECT 1 FROM "membership" m
           JOIN "account" a ON a.id = m.account_id AND a.household_id = jci.household_id
           WHERE m.resident_profile_id = rp.id AND m.household_id = jci.household_id
             AND m.revoked_at IS NULL AND a.email IS NULL
         ))
    )
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION resolve_join_code(text) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION resolve_join_code(text) TO app_runtime;
--> statement-breakpoint

-- Step 5: claim_join_code, now two-argument — the caller STATES which purpose it redeems
-- (design.md Decision 4), so joinHousehold can never spend a reset link and redeemPasswordReset
-- can never spend a joining link, and neither needs a rollback to find out. Both prior overloads
-- (drizzle/0013's one-argument form, and any partial prior run of this file's own two-argument
-- form) are dropped first, so exactly one `claim_join_code` exists afterwards.
DROP FUNCTION IF EXISTS claim_join_code(text);
--> statement-breakpoint
DROP FUNCTION IF EXISTS claim_join_code(text, join_code_purpose);
--> statement-breakpoint
CREATE FUNCTION claim_join_code(p_code text, p_purpose join_code_purpose) RETURNS TABLE (
  household_id uuid,
  issuance_id uuid,
  household_name text,
  bound_resident_profile_id uuid,
  bound_resident_display_name text,
  purpose join_code_purpose
)
LANGUAGE sql SECURITY DEFINER SET search_path = public VOLATILE AS $$
  WITH claimed AS (
    UPDATE "join_code_issuance"
       SET uses = uses + 1
     WHERE code = p_code
       AND purpose = p_purpose
       AND deleted_at IS NULL
       AND expires_at > now()
       AND uses < max_uses
       -- Same predicate as resolve_join_code's WHERE, evaluated in the SAME statement as the
       -- increment so a link that is no longer valid cannot be spent. This does NOT by itself
       -- settle two links racing for one profile (join) or one account (reset): they update
       -- DIFFERENT issuance rows, so nothing serializes them here. The conditional UPDATE on
       -- resident_profile in joinHousehold's bound branch, and the membership/account
       -- `FOR UPDATE` re-check in redeemPasswordReset, are what decide those cases — each takes a
       -- row lock, so the loser matches zero rows and its whole transaction, this increment
       -- included, rolls back.
       AND (
         (purpose = 'join' AND (
           resident_profile_id IS NULL
           OR EXISTS (
             SELECT 1 FROM "resident_profile" rp
             WHERE rp.id = "join_code_issuance".resident_profile_id
               AND rp.household_id = "join_code_issuance".household_id
               AND rp.status = 'prepared'
           )
         ))
         OR
         (purpose = 'password_reset' AND EXISTS (
           SELECT 1 FROM "resident_profile" rp
           JOIN "membership" m ON m.resident_profile_id = rp.id AND m.household_id = "join_code_issuance".household_id
           JOIN "account" a ON a.id = m.account_id AND a.household_id = "join_code_issuance".household_id
           WHERE rp.id = "join_code_issuance".resident_profile_id
             AND rp.household_id = "join_code_issuance".household_id
             AND rp.status = 'active' AND m.revoked_at IS NULL AND a.email IS NULL
         ))
       )
    RETURNING household_id, id AS issuance_id, resident_profile_id, purpose
  )
  SELECT h.id, claimed.issuance_id, h.name, rp.id, rp.display_name, claimed.purpose
  FROM claimed
  JOIN "household" h ON h.id = claimed.household_id
  -- Same household predicate, same reasoning as resolve_join_code above.
  LEFT JOIN "resident_profile" rp
    ON rp.id = claimed.resident_profile_id AND rp.household_id = claimed.household_id
  WHERE h.deleted_at IS NULL
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION claim_join_code(text, join_code_purpose) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION claim_join_code(text, join_code_purpose) TO app_runtime;
