-- Copilot review round 2 (PR #23), CLAUDE.md "The relationship a predicate joins through must
-- itself be enforced" / "Every writer of the same state, pairwise": one membership per resident
-- profile, and one membership per account, were both assumptions held only by the three writers
-- (registerHousehold, claimResidentProfile, joinHousehold in auth.ts) — nothing in the database
-- stopped a second row. The reset path picks `[membershipRow]` by resident_profile_id
-- (issuePasswordResetLink/redeemPasswordReset), and signIn picks it by account_id
-- (`SELECT ... FOR UPDATE` in auth.ts), so a second row for either would make either pick
-- ambiguous — a real bug, not a defensive one, since drizzle-kit generates `db.select()` without
-- an implicit LIMIT.
--
-- Dev data checked immediately before this migration (both queries returned zero rows):
--   SELECT resident_profile_id, count(*) FROM membership
--     WHERE resident_profile_id IS NOT NULL GROUP BY resident_profile_id HAVING count(*) > 1;
--   SELECT account_id, count(*) FROM membership GROUP BY account_id HAVING count(*) > 1;
--
-- Generated by `drizzle-kit generate` from schema.ts's own uniqueIndex() declarations, then
-- hand-edited here for re-runnability (CLAUDE.md "Migrations"): `IF NOT EXISTS`/`IF EXISTS` on
-- every statement, so a partial prior run (or a second run after this file already applied
-- cleanly) is a no-op rather than an error.
--
-- Copilot review round 2 (PR #23): drizzle/0019 now carries its own re-runnable copy of the two
-- CREATE UNIQUE INDEX statements below at the top of that file (fresh-database migration-order
-- fix), so on dev — which already applied 0019 before those lines existed — the two CREATEs here
-- are idempotent RE-ASSERTIONS of indexes dev already has, not new work; only the DROP INDEX above
-- (removing the old non-unique index) is genuinely new here. Left in place rather than removed:
-- a database that somehow reaches 0021 without 0019's new top section still gets both indexes.
--
-- The old plain `membership_account_id_idx` (drizzle/0004) is dropped, not kept alongside the new
-- unique one: a unique index is itself usable for every plain equality lookup the old non-unique
-- one served (Postgres does not need a second, redundant index over the same single column), so
-- nothing in this codebase's query plans loses coverage by removing it.
DROP INDEX IF EXISTS "membership_account_id_idx";
--> statement-breakpoint

-- Partial: a household account's own membership row always has a null resident_profile_id
-- (ADR-013 — the household account never occupies a profile), and there is no invariant limiting
-- how many such null-profile rows exist across different households. "One membership per profile"
-- is a statement about SET profile ids only, which is exactly what a partial unique index over
-- non-null values enforces.
CREATE UNIQUE INDEX IF NOT EXISTS "membership_resident_profile_id_unique" ON "membership" USING btree ("resident_profile_id") WHERE "membership"."resident_profile_id" IS NOT NULL;
--> statement-breakpoint

-- Every membership row names exactly one account.id (no exceptions, no partial predicate needed).
CREATE UNIQUE INDEX IF NOT EXISTS "membership_account_id_unique" ON "membership" USING btree ("account_id");
