/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBewerbungNeuRouteImport } from './routes/_authenticated/bewerbung-neu'
import { Route as AuthenticatedCastingRouteImport } from './routes/_authenticated/casting'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedMitteilungenRouteImport } from './routes/_authenticated/mitteilungen'
import { Route as AuthenticatedRanglisteRouteImport } from './routes/_authenticated/rangliste'
import { Route as AuthenticatedTeilnehmendeRouteImport } from './routes/_authenticated/teilnehmende'
import { Route as AuthenticatedZuhauseRouteImport } from './routes/_authenticated/zuhause'
import { Route as BeitrittCodeRouteImport } from './routes/beitritt.$code'
import { Route as AuthenticatedOrganisationIndexRouteImport } from './routes/_authenticated/organisation/index'
import { Route as AuthenticatedOrganisationMitgliederRouteImport } from './routes/_authenticated/organisation/mitglieder'
import { Route as AuthenticatedOrganisationRegelnRouteImport } from './routes/_authenticated/organisation/regeln'
import { Route as AuthenticatedOrganisationZimmerRouteImport } from './routes/_authenticated/organisation/zimmer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBewerbungNeuRoute =
  AuthenticatedBewerbungNeuRouteImport.update({
    id: '/bewerbung-neu',
    path: '/bewerbung-neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCastingRoute = AuthenticatedCastingRouteImport.update({
  id: '/casting',
  path: '/casting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMitteilungenRoute =
  AuthenticatedMitteilungenRouteImport.update({
    id: '/mitteilungen',
    path: '/mitteilungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRanglisteRoute = AuthenticatedRanglisteRouteImport.update({
  id: '/rangliste',
  path: '/rangliste',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeilnehmendeRoute =
  AuthenticatedTeilnehmendeRouteImport.update({
    id: '/teilnehmende',
    path: '/teilnehmende',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZuhauseRoute = AuthenticatedZuhauseRouteImport.update({
  id: '/zuhause',
  path: '/zuhause',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BeitrittCodeRoute = BeitrittCodeRouteImport.update({
  id: '/beitritt/$code',
  path: '/beitritt/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganisationIndexRoute =
  AuthenticatedOrganisationIndexRouteImport.update({
    id: '/organisation/',
    path: '/organisation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganisationMitgliederRoute =
  AuthenticatedOrganisationMitgliederRouteImport.update({
    id: '/organisation/mitglieder',
    path: '/organisation/mitglieder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganisationRegelnRoute =
  AuthenticatedOrganisationRegelnRouteImport.update({
    id: '/organisation/regeln',
    path: '/organisation/regeln',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganisationZimmerRoute =
  AuthenticatedOrganisationZimmerRouteImport.update({
    id: '/organisation/zimmer',
    path: '/organisation/zimmer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bewerbung-neu': typeof AuthenticatedBewerbungNeuRoute
  '/casting': typeof AuthenticatedCastingRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/mitteilungen': typeof AuthenticatedMitteilungenRoute
  '/rangliste': typeof AuthenticatedRanglisteRoute
  '/teilnehmende': typeof AuthenticatedTeilnehmendeRoute
  '/zuhause': typeof AuthenticatedZuhauseRoute
  '/beitritt/$code': typeof BeitrittCodeRoute
  '/organisation/mitglieder': typeof AuthenticatedOrganisationMitgliederRoute
  '/organisation/regeln': typeof AuthenticatedOrganisationRegelnRoute
  '/organisation/zimmer': typeof AuthenticatedOrganisationZimmerRoute
  '/organisation/': typeof AuthenticatedOrganisationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bewerbung-neu': typeof AuthenticatedBewerbungNeuRoute
  '/casting': typeof AuthenticatedCastingRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/mitteilungen': typeof AuthenticatedMitteilungenRoute
  '/rangliste': typeof AuthenticatedRanglisteRoute
  '/teilnehmende': typeof AuthenticatedTeilnehmendeRoute
  '/zuhause': typeof AuthenticatedZuhauseRoute
  '/beitritt/$code': typeof BeitrittCodeRoute
  '/organisation/mitglieder': typeof AuthenticatedOrganisationMitgliederRoute
  '/organisation/regeln': typeof AuthenticatedOrganisationRegelnRoute
  '/organisation/zimmer': typeof AuthenticatedOrganisationZimmerRoute
  '/organisation': typeof AuthenticatedOrganisationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bewerbung-neu': typeof AuthenticatedBewerbungNeuRoute
  '/_authenticated/casting': typeof AuthenticatedCastingRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/mitteilungen': typeof AuthenticatedMitteilungenRoute
  '/_authenticated/rangliste': typeof AuthenticatedRanglisteRoute
  '/_authenticated/teilnehmende': typeof AuthenticatedTeilnehmendeRoute
  '/_authenticated/zuhause': typeof AuthenticatedZuhauseRoute
  '/beitritt/$code': typeof BeitrittCodeRoute
  '/_authenticated/organisation/mitglieder': typeof AuthenticatedOrganisationMitgliederRoute
  '/_authenticated/organisation/regeln': typeof AuthenticatedOrganisationRegelnRoute
  '/_authenticated/organisation/zimmer': typeof AuthenticatedOrganisationZimmerRoute
  '/_authenticated/organisation/': typeof AuthenticatedOrganisationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bewerbung-neu'
    | '/casting'
    | '/einstellungen'
    | '/mitteilungen'
    | '/rangliste'
    | '/teilnehmende'
    | '/zuhause'
    | '/beitritt/$code'
    | '/organisation/mitglieder'
    | '/organisation/regeln'
    | '/organisation/zimmer'
    | '/organisation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bewerbung-neu'
    | '/casting'
    | '/einstellungen'
    | '/mitteilungen'
    | '/rangliste'
    | '/teilnehmende'
    | '/zuhause'
    | '/beitritt/$code'
    | '/organisation/mitglieder'
    | '/organisation/regeln'
    | '/organisation/zimmer'
    | '/organisation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bewerbung-neu'
    | '/_authenticated/casting'
    | '/_authenticated/einstellungen'
    | '/_authenticated/mitteilungen'
    | '/_authenticated/rangliste'
    | '/_authenticated/teilnehmende'
    | '/_authenticated/zuhause'
    | '/beitritt/$code'
    | '/_authenticated/organisation/mitglieder'
    | '/_authenticated/organisation/regeln'
    | '/_authenticated/organisation/zimmer'
    | '/_authenticated/organisation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BeitrittCodeRoute: typeof BeitrittCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bewerbung-neu': {
      id: '/_authenticated/bewerbung-neu'
      path: '/bewerbung-neu'
      fullPath: '/bewerbung-neu'
      preLoaderRoute: typeof AuthenticatedBewerbungNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casting': {
      id: '/_authenticated/casting'
      path: '/casting'
      fullPath: '/casting'
      preLoaderRoute: typeof AuthenticatedCastingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mitteilungen': {
      id: '/_authenticated/mitteilungen'
      path: '/mitteilungen'
      fullPath: '/mitteilungen'
      preLoaderRoute: typeof AuthenticatedMitteilungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rangliste': {
      id: '/_authenticated/rangliste'
      path: '/rangliste'
      fullPath: '/rangliste'
      preLoaderRoute: typeof AuthenticatedRanglisteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teilnehmende': {
      id: '/_authenticated/teilnehmende'
      path: '/teilnehmende'
      fullPath: '/teilnehmende'
      preLoaderRoute: typeof AuthenticatedTeilnehmendeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zuhause': {
      id: '/_authenticated/zuhause'
      path: '/zuhause'
      fullPath: '/zuhause'
      preLoaderRoute: typeof AuthenticatedZuhauseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/beitritt/$code': {
      id: '/beitritt/$code'
      path: '/beitritt/$code'
      fullPath: '/beitritt/$code'
      preLoaderRoute: typeof BeitrittCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organisation/': {
      id: '/_authenticated/organisation/'
      path: '/organisation'
      fullPath: '/organisation/'
      preLoaderRoute: typeof AuthenticatedOrganisationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organisation/mitglieder': {
      id: '/_authenticated/organisation/mitglieder'
      path: '/organisation/mitglieder'
      fullPath: '/organisation/mitglieder'
      preLoaderRoute: typeof AuthenticatedOrganisationMitgliederRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organisation/regeln': {
      id: '/_authenticated/organisation/regeln'
      path: '/organisation/regeln'
      fullPath: '/organisation/regeln'
      preLoaderRoute: typeof AuthenticatedOrganisationRegelnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organisation/zimmer': {
      id: '/_authenticated/organisation/zimmer'
      path: '/organisation/zimmer'
      fullPath: '/organisation/zimmer'
      preLoaderRoute: typeof AuthenticatedOrganisationZimmerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBewerbungNeuRoute: typeof AuthenticatedBewerbungNeuRoute
  AuthenticatedCastingRoute: typeof AuthenticatedCastingRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedMitteilungenRoute: typeof AuthenticatedMitteilungenRoute
  AuthenticatedRanglisteRoute: typeof AuthenticatedRanglisteRoute
  AuthenticatedTeilnehmendeRoute: typeof AuthenticatedTeilnehmendeRoute
  AuthenticatedZuhauseRoute: typeof AuthenticatedZuhauseRoute
  AuthenticatedOrganisationMitgliederRoute: typeof AuthenticatedOrganisationMitgliederRoute
  AuthenticatedOrganisationRegelnRoute: typeof AuthenticatedOrganisationRegelnRoute
  AuthenticatedOrganisationZimmerRoute: typeof AuthenticatedOrganisationZimmerRoute
  AuthenticatedOrganisationIndexRoute: typeof AuthenticatedOrganisationIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBewerbungNeuRoute: AuthenticatedBewerbungNeuRoute,
  AuthenticatedCastingRoute: AuthenticatedCastingRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedMitteilungenRoute: AuthenticatedMitteilungenRoute,
  AuthenticatedRanglisteRoute: AuthenticatedRanglisteRoute,
  AuthenticatedTeilnehmendeRoute: AuthenticatedTeilnehmendeRoute,
  AuthenticatedZuhauseRoute: AuthenticatedZuhauseRoute,
  AuthenticatedOrganisationMitgliederRoute:
    AuthenticatedOrganisationMitgliederRoute,
  AuthenticatedOrganisationRegelnRoute: AuthenticatedOrganisationRegelnRoute,
  AuthenticatedOrganisationZimmerRoute: AuthenticatedOrganisationZimmerRoute,
  AuthenticatedOrganisationIndexRoute: AuthenticatedOrganisationIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BeitrittCodeRoute: BeitrittCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
